name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: AuthAPI.sln                         
      Project_Directory: AuthAPI.API    
      Project_Path: AuthAPI/AuthAPI.API.csproj                   

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build the application
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ${{ env.Solution_Name }} --no-restore --verbosity normal

    - name: Publish the application
      run: dotnet publish ${{ env.Project_Path }} --configuration Release --output ./publish
