name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest  

    env:
      Solution_Name: AuthAPI.sln                         
      Project_Path: AuthAPI.API/AuthAPI.API.csproj                   

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build the application
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore
